[package]
name    = "execution"
version = "0.1.0"
edition = "2021"
[dependencies]
crossbeam = { workspace = true }
thiserror = { workspace = true }
anyhow    = { workspace = true }
ftlog     = { workspace = true }
protocol  = { path = "../protocol" }
