[package]
name    = "conf"
version = "0.1.0"
edition = "2021"
[dependencies]
serde  = { workspace = true }
anyhow = { workspace = true }
config = "0.14.0"
clap   = { version = "4.5.20", features = [ 'derive' ] }
