[package]
name    = "strategy"
version = "0.1.0"
edition = "2021"
[dependencies]
anyhow         = { workspace = true }
thiserror      = { workspace = true }
derive_builder = { workspace = true }
crossbeam      = { workspace = true }
protocol       = { path = "../protocol" }
