[package]
name    = "market_feed"
version = "0.1.0"
edition = "2021"
[dependencies]
circular-queue = "0.2.6"
yata           = "0.7.0"
anyhow         = { workspace = true }
protocol       = { path = "../protocol" }
derive_builder = { workspace = true }
