[package]
name    = "portfolio"
version = "0.1.0"
edition = "2021"
[dependencies]
uuid           = { workspace = true }
anyhow         = { workspace = true }
protocol       = { path = "../protocol" }
derive_builder = { workspace = true }
