[package]
name    = "utils"
version = "0.1.0"
edition = "2021"
[dependencies]
reqwest    = "0.12.8"
chrono     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
tokio      = { workspace = true }
anyhow     = { workspace = true }
zip = "2.2.0"
csv = "1.3.0"
